import type { Metadata } from "next";
import "./globals.css";
import styles from './ui/homeCliente.module.css'
import Footer from "./ui/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="w-screen h-screen">
        <div className={`grid min-h-full grid-rows-[1fr_auto] ${styles.container}`}>
          <main className='w-screen flex justify-center'>
            <div className='w-screen sm:w-1/3 bg-zinc-200'>
              {children}
            </div>
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
